# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and Deploy React app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: website/package-lock.json
      - name: Install and Build
        working-directory: website
        run: |
          npm ci
          npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: website/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: production-files
          path: website/dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./website/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
